<?php
// $Id$

/**
 * Implements hook_skinr_api().
 */
function skinr_test_skinr_api() {
  return array('api' => 2.0);
}

/**
 * Implements hook_skinr_skin_info().
 */
function skinr_test_skinr_skin_info() {
  $skins['skinr_test_font'] = array(
    'title' => t('Font family'),
    'type' => 'select',
    'group' => 'typography',
    'theme hooks' => array('block', 'region'),
    'attached' => array(
      'css' => array('skinr_test.css'),
    ),
    'options' => array(
      'font_1' => array(
        'title' => 'Arial, Helvetica, Nimbus Sans L, Liberation Sans, FreeSans',
        'class' => array('font-1'),
      ),
      'font_2' => array(
        'title' => 'Lucida Grande, Lucida Sans Unicode, DejaVu Sans, Tahoma',
        'class' => array('font-2'),
      ),
    ),
  );
  return $skins;
}
